Using CUDA
Unnamed: 0                                                  927
index                                                       927
Id1                                                      Q9Y678
Id2                                                      P53618
Interact                                                      1
sequence_a    MLKKFDKKDEESGGGSNPFQHLEKSAVLQEARVFNETPINPRKCAH...
sequence_b    MTAAENVCYTLINVPMDSEPPSEISLKNDLEKGDVKSKTEALKKVI...
Name: 735, dtype: object
/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/torch/cuda/__init__.py:611: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    for batch in dataloader:
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nfs/home/students/t.reim/bachelor/pytorchtest/data/data.py", line 297, in __getitem__
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)