Traceback (most recent call last):
  File "main.py", line 49, in <module>
    dataset = d.MyDataset(train_data, max)
  File "/nfs/home/students/t.reim/bachelor/pytorchtest/data/data.py", line 265, in __init__
    self.df = pd.read_csv(filename)  # Load the data from the CSV file
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/nfs/home/students/t.reim/.conda/envs/mamba2/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/nfs/home/students/t.reim/bachelor/pytorchtest/data/train_all_seq_1166.csv'